### PR TITLE
Version 1.2.0

### PR DESCRIPTION
**Pull request by yafuquen**
## Description
- Allow persisting factors after reinstall
- Silently approve challenges for a factor

## Testing
- [ ] Added unit tests
- [x] Ran unit tests successfully
- [x] Added documentation for public APIs and/or Wiki

### CODE REVIEW

**Review by AlejandroOrozco — APPROVED** [review]

**Review by mejiagarcia — APPROVED** [review]
I just ran this branch and tested the silent approvals in foreground and seems working as expected

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.18%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift | **`84.62%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.14%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift | **`84.62%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.14%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift | **`84.62%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
