### PR TITLE
[Housekeeping] - Fixed DemoApp compilation

### PR DESCRIPTION
**Pull request by sanarroya**
## Description
- Fixes DemoApp compilation

## Commit message
- chore: Fixed DemoApp compilation

## Testing
- [ ] Added unit tests
- [x] Ran unit tests successfully
- [ ] Added documentation for public APIs and/or Wiki

### CODE REVIEW

**Comment by SergioFierro** [comment]
Commit message `chore: Fix Cocoapods release`
Is it correct?

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.50%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by sanarroya** [comment]
> Commit message `chore: Fix Cocoapods release`
> Is it correct?

The commit message is correct, I just put the wrong one on the description but it has the right one now

**Review by yafuquen — APPROVED** [review]

**Review by SergioFierro — APPROVED** [review]

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.50%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
