### PR TITLE
feat: Support react native bridge

### PR DESCRIPTION
**Pull request by yafuquen**
## Jira Ticket
- ACCSEC-19645

## Description
- Add properties for SDK version name, version code and bundle name to prevent override by react native module. Update SDK version read

## Commit message
-  feat: Support react native bridge

## Testing
- [ ] Added unit tests
- [ ] Ran unit tests successfully
- [ ] Added documentation for public APIs and/or Wiki

### CODE REVIEW

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.38%`**
File | Coverage
-----|-----
TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift | **`99.33%`**
TwilioVerify/TwilioVerify/Sources/Networking/RequestHelper.swift | **`100.00%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.38%`**
File | Coverage
-----|-----
TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift | **`99.33%`**
TwilioVerify/TwilioVerify/Sources/Networking/RequestHelper.swift | **`100.00%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by Greshot — APPROVED** [review]

**Review by Greshot — COMMENTED** [review]
@yafuquen Integrations tests in All devices are failing. Is it happening because of this change? Can you please take a look at it?

**Comment by yafuquen** [comment]
> @yafuquen Integrations tests in All devices are failing. Is it happening because of this change? Can you please take a look at it?

Passing now, it was a firebase error with one device

**Review by SergioFierro — APPROVED** [review]

**Pull request merged**
