### PR TITLE
[ACCSEC-21700] - Improve readability for network errors

### PR DESCRIPTION
**Pull request by AlejandroOrozco**
## Jira Ticket
- ACCSEC-21700

## Github Issue
- ISSUE-

## Description

- Make FailureResponse public.
- Provide full errorDescription for TwilioVerifyErrors that were originated by a NetworkError.

## Commit message
-  feat: Improve network errors readability

## Testing
- [ ] Added unit tests
- [ ] Ran unit tests successfully
- [ ] Added documentation for public APIs and/or Wiki

### CODE REVIEW

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.16%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Extensions/URLSession+Extensions.swift | **`92.31%`**
TwilioVerifySDK/TwilioVerify/Sources/Networking/Models/Response.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/TwilioVerifyError.swift | **`93.15%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by yafuquen — APPROVED** [review]

**Review by SergioFierro — APPROVED** [review]

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.16%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Extensions/URLSession+Extensions.swift | **`92.31%`**
TwilioVerifySDK/TwilioVerify/Sources/Networking/Models/Response.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/TwilioVerifyError.swift | **`93.15%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.16%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Extensions/URLSession+Extensions.swift | **`92.31%`**
TwilioVerifySDK/TwilioVerify/Sources/Networking/Models/Response.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/TwilioVerifyError.swift | **`93.15%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.16%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Extensions/URLSession+Extensions.swift | **`92.31%`**
TwilioVerifySDK/TwilioVerify/Sources/Networking/Models/Response.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/TwilioVerifyError.swift | **`93.15%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.16%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Extensions/URLSession+Extensions.swift | **`92.31%`**
TwilioVerifySDK/TwilioVerify/Sources/Networking/Models/Response.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/TwilioVerifyError.swift | **`93.15%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.16%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Extensions/URLSession+Extensions.swift | **`92.31%`**
TwilioVerifySDK/TwilioVerify/Sources/Networking/Models/Response.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/TwilioVerifyError.swift | **`93.15%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by yafuquen — APPROVED** [review]

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.16%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Extensions/URLSession+Extensions.swift | **`92.31%`**
TwilioVerifySDK/TwilioVerify/Sources/Networking/Models/Response.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/TwilioVerifyError.swift | **`93.15%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.16%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Extensions/URLSession+Extensions.swift | **`92.31%`**
TwilioVerifySDK/TwilioVerify/Sources/Networking/Models/Response.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/TwilioVerifyError.swift | **`93.15%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AlejandroOrozco** [comment]
Closing ticket while we research a fix for underlaying issues at ACCSEC-21820

**Pull request closed without merging**
