### PR TITLE
version 1.3.0

### PR DESCRIPTION
**Pull request by mejiagarcia**
version 1.3.0

## Description
- feat: Support notification platform "none" to allow not sending push token. Factors with notification platform "none" will not receive push notifications for challenges and polling should be implemented to get pending challenges

## Testing
- [x] Added unit tests
- [x] Ran unit tests successfully
- [x] Added documentation for public APIs and/or Wiki

### CODE REVIEW

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.15%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorFacade.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/PushFactory.swift | **`98.83%`**
TwilioVerifySDK/TwilioVerify/Sources/Models/FactorPayload.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/Models/UpdateFactorPayload.swift | **`100.00%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.16%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorFacade.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorMapper.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/Models/PushFactor.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/PushFactory.swift | **`98.83%`**
TwilioVerifySDK/TwilioVerify/Sources/Models/FactorPayload.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/Models/UpdateFactorPayload.swift | **`100.00%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AuthyApps** [comment]
## Code coverage
### Total coverage: **`95.18%`**
File | Coverage
-----|-----
TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorFacade.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorMapper.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/Models/PushFactor.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/PushFactory.swift | **`98.83%`**
TwilioVerifySDK/TwilioVerify/Sources/Models/FactorPayload.swift | **`100.00%`**
TwilioVerifySDK/TwilioVerify/Sources/Models/UpdateFactorPayload.swift | **`100.00%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by AlejandroOrozco — APPROVED** [review]
LGTM 👍

**Review by yafuquen — APPROVED** [review]

**Pull request merged**
